language: python
python:
  - "2.7"
  - "3.3"
env:
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.5.1
install:
  - pip install -e .
  - pip install --use-mirrors flake8 Django==$DJANGO_VERSION
script:
  - django-admin.py test --settings=inspect_model.test_settings
  - flake8 inspect_model
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO_VERSION=1.3.7
    - python: "3.3"
      env: DJANGO_VERSION=1.4.5
